import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "./component";

// import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import "./Utilis/lib/animate/animate.css"
import "./Utilis/lib/animate/animate.min.css"
import "./globals.css";
import "./Utilis/lib/animate/bootstrap.min.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
